# Natural Language Process(NLP)
- Makine ile insan arasında ki iletişimi sağlamak için oluşturulmuş bir machine learning yöntemidir.
- Cleanin Data
- Bag Of Words
- Text Classification
<br><br>
- Nerelerde Kullanılır:
- - Predict genre of book
- - Question - Answer
- - Summarization Of Book

In [8]:
import pandas as pd
import numpy as np
import re

data = pd.read_csv(r"gender_classifier.csv",encoding="latin1")
data

_unit_id  _golden _unit_state  _trusted_judgments _last_judgment_at  \
0      815719226    False   finalized                   3    10/26/15 23:24   
1      815719227    False   finalized                   3    10/26/15 23:30   
2      815719228    False   finalized                   3    10/26/15 23:33   
3      815719229    False   finalized                   3    10/26/15 23:10   
4      815719230    False   finalized                   3     10/27/15 1:15   
...          ...      ...         ...                 ...               ...   
20045  815757572     True      golden                 259               NaN   
20046  815757681     True      golden                 248               NaN   
20047  815757830     True      golden                 264               NaN   
20048  815757921     True      golden                 250               NaN   
20049  815757985     True      golden                 249               NaN   

       gender  gender:confidence profile_yn  profile_yn:confidence  \
0        male             1.0000        yes                    1.0   
1        male             1.0000        yes                    1.0   
2        male             0.6625        yes                    1.0   
3        male             1.0000        yes                    1.0   
4      female             1.0000        yes                    1.0   
...       ...                ...        ...                    ...   
20045  female             1.0000        yes                    1.0   
20046    male             1.0000        yes                    1.0   
20047    male             1.0000        yes                    1.0   
20048  female             0.8489        yes                    1.0   
20049  female             1.0000        yes                    1.0   

              created  ...                                       profileimage  \
0        12/5/13 1:48  ...  https://pbs.twimg.com/profile_images/414342229...   
1       10/1/12 13:51  ...  https://pbs.twimg.com/profile_images/539604221...   
2      11/28/14 11:30  ...  https://pbs.twimg.com/profile_images/657330418...   
3       6/11/09 22:39  ...  https://pbs.twimg.com/profile_images/259703936...   
4       4/16/14 13:23  ...  https://pbs.twimg.com/profile_images/564094871...   
...               ...  ...                                                ...   
20045    8/5/15 21:16  ...  https://pbs.twimg.com/profile_images/656793310...   
20046   8/15/12 21:17  ...  https://pbs.twimg.com/profile_images/639815429...   
20047     9/3/12 1:17  ...  https://pbs.twimg.com/profile_images/655473271...   
20048   11/6/12 23:46  ...  https://pbs.twimg.com/profile_images/657716093...   
20049   4/14/14 17:22  ...  https://pbs.twimg.com/profile_images/655134724...   

       retweet_count sidebar_color  \
0                  0        FFFFFF   
1                  0        C0DEED   
2                  1        C0DEED   
3                  0        C0DEED   
4                  0             0   
...              ...           ...   
20045              0        C0DEED   
20046              0             0   
20047              0        C0DEED   
20048              0             0   
20049              0        C0DEED   

                                                    text tweet_coord  \
0      Robbie E Responds To Critics After Win Against...         NaN   
1      ‰ÛÏIt felt like they were my friends and I was...         NaN   
2      i absolutely adore when louis starts the songs...         NaN   
3      Hi @JordanSpieth - Looking at the url - do you...         NaN   
4      Watching Neighbours on Sky+ catching up with t...         NaN   
...                                                  ...         ...   
20045  @lookupondeath ...Fine, and I'll drink tea too...         NaN   
20046  Greg Hardy you a good player and all but don't...         NaN   
20047  You can miss people and still never want to se...         NaN   
20048  @bitemyapp i had noticed your tendency to pee ...         NaN

In [9]:
data = pd.concat([data.gender,data.description],axis=1) # axis=1 for columns
data.dropna(axis=0,inplace=True)
data

gender                                        description
0        male                              i sing my own rhythm.
1        male  I'm the author of novels filled with family dr...
2        male                louis whining and squealing and all
3        male  Mobile guy.  49ers, Shazam, Google, Kleiner Pe...
4      female  Ricky Wilson The Best FRONTMAN/Kaiser Chiefs T...
...       ...                                                ...
20045  female                                               (rp)
20046    male  Whatever you like, it's not a problem at all. ...
20047    male  #TeamBarcelona ..You look lost so you should f...
20048  female  Anti-statist; I homeschool my kids. Aspiring t...
20049  female                     Teamwork makes the dream work.

[16224 rows x 2 columns]

In [6]:
# male = 0
# female = 1
data.gender = [1 if each == "male" else 0 for each in data.gender]
data

gender                                        description
0           1                              i sing my own rhythm.
1           1  I'm the author of novels filled with family dr...
2           1                louis whining and squealing and all
3           1  Mobile guy.  49ers, Shazam, Google, Kleiner Pe...
4           0  Ricky Wilson The Best FRONTMAN/Kaiser Chiefs T...
...       ...                                                ...
20045       0                                               (rp)
20046       1  Whatever you like, it's not a problem at all. ...
20047       1  #TeamBarcelona ..You look lost so you should f...
20048       0  Anti-statist; I homeschool my kids. Aspiring t...
20049       0                     Teamwork makes the dream work.

[16224 rows x 2 columns]

In [5]:
# cleaning
## regular expression
import re

# for example
first_description = data.description[4]
first_description

'Ricky Wilson The Best FRONTMAN/Kaiser Chiefs The Best BAND Xxxx Thank you Kaiser Chiefs for an incredible year of gigs and memories to cherish always :) Xxxxxxx'

In [51]:
description = re.sub("[^a-zA-Z]"," ",first_description)
description

'Ricky Wilson The Best FRONTMAN Kaiser Chiefs The Best BAND Xxxx Thank you Kaiser Chiefs for an incredible year of gigs and memories to cherish always    Xxxxxxx'

In [52]:
description = description.lower() # küçük harfe çevirme
description

'ricky wilson the best frontman kaiser chiefs the best band xxxx thank you kaiser chiefs for an incredible year of gigs and memories to cherish always    xxxxxxx'

In [53]:
# stopword : gereksiz kelimeler
from nltk.corpus import stopwords
import nltk # natural language tool kit
# nltk.download("stopwords") # corpus adlı bir klasöre indiriliyor

In [54]:
# description = description.split()

In [55]:
# split yerine tokenizer kullanabiliriz
description = nltk.word_tokenize(description)
description

['ricky',
 'wilson',
 'the',
 'best',
 'frontman',
 'kaiser',
 'chiefs',
 'the',
 'best',
 'band',
 'xxxx',
 'thank',
 'you',
 'kaiser',
 'chiefs',
 'for',
 'an',
 'incredible',
 'year',
 'of',
 'gigs',
 'and',
 'memories',
 'to',
 'cherish',
 'always',
 'xxxxxxx']

In [56]:
# gereksiz kelimeleri at (at,the gibi)
description = [word for word in description if not word in set(stopwords.words("english"))]

In [11]:
# lemmatazation : kökleri bulma
import nltk as nlp
lemma = nlp.WordNetLemmatizer()
description = [ lemma.lemmatize(word) for word in description]

description = " ".join(description)

In [12]:
description

'i   s i n g   m y   o w n   r h y t h m  '

---

In [1]:
import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
import nltk 
import nltk as nlp

data = pd.read_csv(r"gender_classifier.csv",encoding="latin1")
data = pd.concat([data.gender,data.description],axis=1) # axis=1 for columns
data.dropna(axis=0,inplace=True)
data.gender = [1 if each == "male" else 0 for each in data.gender]

In [2]:
# Bütün datalar için;
description_list = []
for description in data.description:
    description = re.sub("[^a-zA-Z]"," ", description)
    description = description.lower()
    description = nltk.word_tokenize(description)
    #description = [word for word in description if not word in set(stopwords.words("english"))]
    # yukarıda ki yapıyı aşağıda daha hızlı çalıştırılan bir metoda yazdık
    lemma = nlp.WordNetLemmatizer()
    description = [ lemma.lemmatize(word) for word in description ]
    description = " ".join(description)
    description_list.append(description)

In [3]:
# bag of words
# 1-ben okula döndüm
# 2-ben yarın okula dönüceğim
# 3-yarın okulda ne işin var
# cümleler    ben okul dönmek yarın ne iş var
#    1         1   1     1      0   0  0   0
#    2         1   1     1      1   0  0   0
#    3         0   1     0      1   1  1   1

from sklearn.feature_extraction.text import CountVectorizer # bag of words için kullanılan metod
max_features = 5000 # 32000 kelimenin içerisinden en çok kullanılan 5000 kelime
count_vectorizer = CountVectorizer(max_features=max_features,stop_words="english")
# CountVectorizer(max_feature=max_feature,stop_words="english",lowercase=true,token_pattern="[^a-zA-Z]")
sparce_matrix = count_vectorizer.fit_transform(description_list).toarray() # 0 ve 1

In [4]:
# print("en sık kullanılan {} kelimeler: {}".format(max_features,count_vectorizer.get_feature_names()))

In [5]:
# text classification
y = data.iloc[:,0].values # kadın erkek
y

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [6]:
x = sparce_matrix # kelimeler için 0-1
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [7]:
# train test split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=42)

print("x_train",x_train.shape)
print("x_test",x_test.shape)
print("y_train",y_train.shape)
print("y_test",y_test.shape)

x_train (14601, 5000)
x_test (1623, 5000)
y_train (14601,)
y_test (1623,)


In [17]:
# naive bayes
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(x_train,y_train)

# prediction
y_pred = nb.predict(x_test)
print("Accuracy: ", nb.score(x_test,y_test)*100)

Accuracy:  45.40973505853358


In [9]:
y_pred

array([1, 1, 1, ..., 0, 0, 1], dtype=int64)